// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onColorChange();
void onTemperatureChange();
void onColorLightChange();
void onDistanceChange();

CloudColor color;
float temperature;
CloudColoredLight color_light;
int distance;

void initProperties(){

  ArduinoCloud.addProperty(color, READWRITE, ON_CHANGE, onColorChange);
  ArduinoCloud.addProperty(temperature, READWRITE, ON_CHANGE, onTemperatureChange);
  ArduinoCloud.addProperty(color_light, READWRITE, ON_CHANGE, onColorLightChange);
  ArduinoCloud.addProperty(distance, READWRITE, ON_CHANGE, onDistanceChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
